Repository hyperledger/aries-rfcs, pull requests merged in 2021-03, with the labels that each got.

#594 Indy attachments RFC
  features/0453-issue-credential-v2/README.md
  features/0454-present-proof-v2/README.md
  features/0592-indy-attachments/README.md
Labels: WIP

#610 add media type details to RFC 587
  features/0587-encryption-envelope-v2/README.md
Labels: AIP 2.0

#606 Make plaintext MIME type more specific by default
  features/0044-didcomm-file-and-mime-types/README.md
Labels: AIP 2.0

#607 Rfc592 cred proposal filter
  features/0453-issue-credential-v2/README.md
  features/0592-indy-attachments/README.md
Labels: AIP 2.0

#602 RFC 592: touch up indy structures and text
  features/0592-indy-attachments/README.md
Labels: AIP 2.0

#622 implied mime type (in value of typ/cty) prefix
  features/0044-didcomm-file-and-mime-types/README.md
Labels: AIP 2.0

#620 RFC0067: add accept property to indicate media type
  features/0067-didcomm-diddoc-conventions/README.md
Labels: AIP 2.0

#595 RFC0434: add accept property to indicate media type
  features/0434-outofband/README.md
Labels: AIP 2.0

#621 RFC 0587: transition and AIP impacts
  features/0587-encryption-envelope-v2/README.md
Labels: AIP 2.0

#619 Goal codes in credential exchange protocols
  features/0453-issue-credential-v2/README.md
  features/0454-present-proof-v2/README.md
Labels: AIP 2.0

#600 Rfc 454 tweaks
  features/0454-present-proof-v2/README.md
  features/0511-dif-cred-manifest-attach/README.md
Labels: AIP 2.0

#608 rfc0023: mark `did` as required
  features/0023-did-exchange/README.md
Labels: AIP 2.0

#593 RFC 0593: JSON-LD Credential Attachment format for requesting and presenting credentials
  features/0453-issue-credential-v2/README.md
  features/0593-json-ld-cred-attach/README.md
  index.md
Labels: AIP 2.0

#588 RFC0360: add RFC0211 and 0434 to the list
  features/0360-use-did-key/README.md
Labels: AIP 2.0

#564 tweak notation for better terminology
  concepts/0006-ssi-notation/README.md
  concepts/0006-ssi-notation/negotiation-pattern.png
  concepts/0006-ssi-notation/taxonomy.png
Labels: Need Vote

#575 refactor: RFC 334 Add NIST P and X25519 keys concrete examples
  features/0334-jwe-envelope/README.md
  features/0334-jwe-envelope/anoncrypt-examples.md
  features/0334-jwe-envelope/authcrypt-examples.md
Labels: AIP 2.0
