Repository hyperledger/aries-rfcs, pull requests merged in 2021-05, with the labels that each got.

#639 clarify URL shortening
  features/0434-outofband/README.md
Labels: AIP 2.0

#644 simplify please ack decorator
  features/0317-please-ack/README.md
  features/0453-issue-credential-v2/README.md
  features/0454-present-proof-v2/README.md
Labels: AIP 2.0

#561 substantive, controversial change: total base64url consistency in repo
  concepts/0017-attachments/README.md
  concepts/0029-message-trust-contexts/README.md
  concepts/0074-didcomm-best-practices/README.md
  concepts/0104-chained-credentials/README.md
  concepts/0268-unified-didcomm-agent-deeplinking/README.md
  concepts/0346-didcomm-between-two-mobile-agents/README.md
  features/0036-issue-credential/README.md
  features/0037-present-proof/README.md
  features/0075-payment-decorators/README.md
  features/0113-question-answer/README.md
  features/0116-evidence-exchange/README.md
  features/0347-proof-negotiation/README.md
  features/0453-issue-credential-v2/README.md
Labels: AIP 2.0, question

#650 Changed public DID language, removed GUID requirement in URL
  features/0434-outofband/README.md
Labels: AIP 2.0

#651 Added Method 2 to Static Peer DIDs
  features/0627-static-peer-dids/README.md
Labels: AIP 2.0

#661 Remove extra URI types for links
  concepts/0017-attachments/README.md
Labels: AIP 2.0

#666 Clarify text for did:key encoding - incorrect prefix per #664
  features/0360-use-did-key/README.md
Labels: AIP 2.0

#660 RFC 587: update to ecdh-1pu draft 04
  features/0587-encryption-envelope-v2/README.md
Labels: AIP 2.0

#652 RFC0510: updates
  features/0510-dif-pres-exch-attach/README.md
  features/0593-json-ld-cred-attach/README.md
Labels: AIP 2.0

#668 Further clarification for #664 about multicodec handling
  features/0360-use-did-key/README.md
Labels: AIP 2.0

#672 add goal code to didx request
  features/0023-did-exchange/README.md
Labels: AIP 2.0

#674 add P curve to RFC 0510
  features/0510-dif-pres-exch-attach/README.md
Labels: AIP 2.0

#676 Add note about BbsBlsSignatureProof2020 ldp_vc to RFC 0510
  features/0510-dif-pres-exch-attach/README.md
Labels: AIP 2.0

#675 Add P Curves to RFC 0593
  features/0593-json-ld-cred-attach/README.md
Labels: AIP 2.0

#579 WIP First cut of the AIP 2.0 list of RFC versions to be included
  concepts/0302-aries-interop-profile/README.md
Labels: AIP 2.0, WIP
